See about triggering a grpc ruby install

diff --git a/scripts/install_core b/scripts/install_core
--- a/scripts/install_core
+++ b/scripts/install_core
@@ -61,8 +61,20 @@ __grpc_install_with_brew() {
     __grpc_brew_install --HEAD grpc
 }
 
+__grpc_install_ruby() {
+    which 'ruby' >> /dev/null || {
+        echo "Could not detect ruby; please install it or add to the PATH and try again";
+        return 1;
+    }
+    gem install grpc -- --with-grpc-dir=$HOME/.linuxbrew
+}
+
 main() {
     echo "Args were: $@";
+    if [ "$@" ~= 'ruby' ] then;
+       echo "ruby required! "
+       __grpc_install_ruby;
+    fi
     __grpc_check_for_brew || exit 1;
     __grpc_install_with_brew;
 }
